// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWalLh6l7BdLvgTrWolC3hYiQHI5pnKBo',
    appId: '1:1005354509282:web:427b0201063113e9124fbb',
    messagingSenderId: '1005354509282',
    projectId: 'tr-athletic-development',
    authDomain: 'tr-athletic-development.firebaseapp.com',
    storageBucket: 'tr-athletic-development.firebasestorage.app',
    measurementId: 'G-KDYJSLDHPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0p9tbVeKTRx2aMluqcLkXmBKZb5LohA',
    appId: '1:1005354509282:android:20d86e57431d768b124fbb',
    messagingSenderId: '1005354509282',
    projectId: 'tr-athletic-development',
    storageBucket: 'tr-athletic-development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC39TAhvkSGkAmGIIT34xqtj-kKup8YgZE',
    appId: '1:1005354509282:ios:cd59b4fe99bd9d85124fbb',
    messagingSenderId: '1005354509282',
    projectId: 'tr-athletic-development',
    storageBucket: 'tr-athletic-development.firebasestorage.app',
    iosBundleId: 'com.example.trAtheleticDevelopment',
  );
}
